---
name: ðŸ“„ List Current Microsoft Product IDs
on: workflow_dispatch
jobs:
  list-microsoft-product-ids:
    name: ðŸ“„ List Product IDs from Microsoft
    runs-on: windows-latest
    steps:
      - name: ðŸ“¥ Get Product IDs from Microsoft
        id: get-product-id
        shell: pwsh
        run: |
          Install-Module -Name Microsoft.Graph -Force -AllowClobber -Scope AllUsers -Confirm
          Select-MgProfile -Name "beta"
          Get-PartnerProduct -Catalog 'Software','SoftwarePerpetual','SoftwareSubscriptions' | Format-Table -AutoSize
